models:
  kimi-k2-instruct:
    backends:
      default:1: 
        base_url: https://cloud.infini-ai.com/maas
        url_path_chat: /v1/chat/completions
        # if not set, read from env var OCTOLLM_API_KEY
        # api_key: sk-xxxx
    repeat_detection:
        enabled: true
        min_repeat_len: 1
        max_repeat_len: 5
        repeat_threshold: 50
        block_on_detect: false  # 是否拦截重复内容，默认 false（只记录日志不拦截）
        block_message: "Repeated content detected, please adjust and try again. "  # 拦截时返回的消息
        moderate_stream_every: 50